Module5
art-snail/thinknetica_artsnail pull request #3
Opened 2017-08-14 12:11 UTC by art-snail

2017-08-14 13:50 UTC, vkurennov requested changes

2017-08-14 13:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == @answer.user
* Т.к. проверка на авторство будет встречаться часто, рекомнедую сделать метод в модели User, чтобы можно было вызвать примерно так: `current_user.author_of?(@answer)`.И не забудь на этот метод написать тесты модели.
* Нужно сравнивать по id, чтобы не грузить пользователя из базы лишний раз.

2017-08-14 13:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      redirect_to question_path @question
Редирект одинаковый, зачем его дублировать в условиях

2017-08-14 13:50 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user == @question.user
Замени на вызов `User#author_of?`

2017-08-14 13:50 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to question_path @question
Можно просто `redirect_to @question` - это то же самое.

2017-08-14 13:50 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +- if current_user && answer.user === current_user
Замени на вызов `User#author_of?` И зачем тут `===`?

2017-08-14 13:50 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +  = link_to 'Удалить ответ', [answer.question, answer], method: :delete
чтобы не писать такие странные конструкции, объяви в роутах ресурс answers как shallow, тогда не придется передавать вопрос там, где он не нужен. См. [здесь](http://guides.rubyonrails.org/routing.html#nested-resources) раздел 2.7.2 Shallow Nesting

2017-08-14 13:50 UTC, vkurennov commented on app/views/answers/_form.html.slim
> += form_for [@question, @answer] do |f|
нужен вывод ошибок валидации модели

2017-08-14 13:50 UTC, vkurennov commented on app/views/questions/_form.html.slim
> += form_for @question do |f|
Тут нужен вывод ошибок валидации

2017-08-14 13:50 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +  #{link_to 'Подробнее', question_path(question)}
Зачем тут интерполяция? В slim руби вставки работают через `= `

2017-08-14 13:50 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +h3 #{question.title}
Тут не нужна интерполяция, используй `=`

2017-08-14 13:50 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if @question.user === current_user
Замени на вызов `User#author_of?`

2017-08-14 13:50 UTC, vkurennov commented on config/routes.rb
>      resources :answers
Вот тут примени shallow

2017-08-14 13:50 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +feature 'Create answer', %q{
Нужен тест на невалидный ответ - проверить, что система сообщает об ошибках валидации

2017-08-14 13:50 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Нужен тест на невалидный вопрос - проверить, что система сообщает об ошибках валидации

2017-08-14 13:50 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question successfully'
Тут нужно проверить наличие тектса и заголовка вопроса на странице

2017-08-14 13:50 UTC, vkurennov commented on spec/acceptance/remove_answer_spec.rb
> +    expect(page).to have_content 'Ответ успешно удалён.'
Нужно проверить, что удаленного ответа больше нет на странице

2017-08-14 13:50 UTC, vkurennov commented on spec/acceptance/remove_question_spec.rb
> +    expect(page).to have_content 'Вопрос успешно удалён.'
Нужно проверить, что вопроса больше нет на странице

2017-08-14 13:50 UTC, vkurennov commented on spec/acceptance/show_question_spec.rb
> +    expect(page).to have_content "Вопрос: #{question.title}"
Тут нужно проверять именно список вопросов. Создай штук 5 ответов через create_list и в цикле проверь, что они все есть на странице.
И при этом, все вопросы должны быть разными, для этого используй sequence в фабриках

2017-08-14 13:50 UTC, vkurennov commented on spec/acceptance/view_question_list_spec.rb
> +    expect(page).to have_content 'Список вопросов'
Это ты заголовок страницы проверил, но этого мало. Надо сам контент, т.е. списов вопросов проверять. И, кстати, у тебя 2 теста получается на список вопросов и ни одного на список ответов.

2017-08-14 13:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'valid data' do
Тут нужен тест, проверяющий связь с залогиненным юзером

2017-08-14 13:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    it 'the answer is deleted' do
Тут должно быть 2 контекста: автор удаляет ответ и не-автор

2017-08-14 13:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question), user_id: @user } }
Нет, user_id не передается в параметрах, мы его берем непосредсвенно в контроллере.

2017-08-14 13:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
Тут должно быть 2 контекста: для автора и для не-автора

2017-08-16 09:21 UTC, vkurennov requested changes

2017-08-16 09:21 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user.author_of?(@answer.user.id)
1. Так теряется весь смысл проверки по id, ведь ты вновь вызываешь `@answer.user`, т.е. загружаешь юзера из базы. А идея в том, чтобы этого не делать, ведь достаточно сравнить id и при этом у @answer уже есть поле user_id, которое и содержит нужное значение.
2. Тут нарушается принцип инкапсуляции. Ты должен вызывать метод вот так: `current_user.author_of?(@answer)`, а как там происходит сравнение и по каким полям - это уже внутренняя логика самого метода, вызвающий код не должен об этом знать.

2017-08-16 09:21 UTC, vkurennov commented on app/models/user.rb
> +  def author_of?(resource_id)
Метод должен принимать объект, а не его id

2017-08-16 09:21 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +-unless answer.id.blank?
Используй метод `persisted?`, чтобы проверять сохаренен ли объект в базе

2017-08-16 09:21 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +            .to change(Answer, :count)
to_not change

2017-08-16 09:21 UTC, vkurennov commented on spec/models/user_spec.rb
> +    user = User.new(email: 'test@test.te', password: '12345678')
Используй фабрики в тестах и let

2017-08-16 09:21 UTC, vkurennov commented on spec/models/user_spec.rb
> +    expect(user.author_of?(question.user.id)).to eq true
Нужно проверять все возможные варианты: в каком случае возвращается true и в каком false (2 отдельных теста).

2017-08-16 09:21 UTC, vkurennov commented on spec/models/user_spec.rb
> +    expect(user.author_of?(question.user.id)).to eq true
* rspec делает динамические метчеры (методы для проверки) для методов-предикатов (это методы, которые заканчиваются на знак вопроса и возвращают true/false) и можно писать короче и красивее:
`expect(user).to be_author_of(question)`
т.е. название метчера получается из названия метода без вопр. знака и с доавлением `be_` в начале

2017-08-16 10:27 UTC, art-snail commented on app/views/questions/_question.html.slim
> +  #{link_to 'Подробнее', question_path(question)}
Я пока на разобрался, как 2 переменные и/или переменную и текст произвольный в один тег поместить бе интерполяции

2017-08-16 15:12 UTC, vkurennov approved these changes

2017-08-17 12:24 UTC, merged