Mod10
art-snail/thinknetica_artsnail pull request #8
Opened 2017-09-08 11:36 UTC by art-snail

2017-09-08 17:04 UTC, darialapina requested changes
Помимо комментов по коду, есть ещё два момента:
1. Из-за добавления поля ввода комментария у тебя падает тест редактирования ответа.
Перед сдачей всегда запускай все тесты полностью, не только свеженаписанные.
2. Косяк в файле app/views/common/_attachment.html.slim
Всё падает, если незалогиненый пользователь смотрит страницу вопроса с аттачем (или ответ с аттачем). По-хорошему, раз тут что-то упало, нужно написать тест.

2017-09-08 17:04 UTC, darialapina commented on app/assets/javascripts/templates/answer.jst.skim
> +  a href="/answers/#{@answer.id}/set_best" data-method='patch' data-remote='true' rel='nofollow' Пометить как лучший
Ты эту ссылку покажешь всем, не только автору вопроса.

2017-09-08 17:04 UTC, darialapina commented on app/assets/javascripts/templates/answer.jst.skim
> +      = render 'comments/form', resource: answer
Это не работает. Хэлперы rails в skim шаблонах невозможно использовать.

2017-09-08 17:04 UTC, darialapina commented on app/views/comments/create.js.erb
> +  $('.comments').after("<%=  j render(@comment) %>");
У тебя комментарии к вопросу и к ответам на вопрос добавляются сразу во все списки комментов на странице. Поэтому тесты проходят.
Так же строчка выше выводит сообщение сразу во все div'ы с классом comment-notice.

2017-09-08 17:04 UTC, darialapina commented on app/views/questions/show.html.slim
> +  = render @question.comments.order(updated_at: :desc)
Тут, вероятно, отступ забыл, нет?

2017-09-08 17:04 UTC, darialapina commented on spec/acceptance/answers/create_answer_spec.rb
> +        expect(page).to have_content 'Комментарии:'
Тут проверка пройдёт, ещё и потому, что 'Комментарии:' встречаются для самого вопроса.

2017-09-08 17:04 UTC, darialapina commented on spec/acceptance/answers/create_answer_spec.rb
> +      end
Можно добавить третью сессию, для другого залогиненого пользователя и у него проверять появление ответа с формой комментирования и кнопок голосования.

2017-09-08 17:04 UTC, darialapina commented on app/views/comments/create.js.erb
> +  $('#comment_body').val('');
Тут очищается только форма для коммента к вопросу, тк она выше.

2017-09-08 17:04 UTC, darialapina commented on spec/acceptance/create_comment_spec.rb
> +          expect(page).to have_content 'Мой комментарий'
Как уже писала в комментарии выше, тесты проходят из-за добавления и комментария и сообщения сразу везде.

2017-09-08 17:04 UTC, darialapina commented on app/assets/javascripts/comments.coffee
> +            el = $('.comments')
Коммент для вопроса добавляется и в комменты для ответов.

2017-09-09 09:12 UTC, vkurennov requested changes

2017-09-09 09:12 UTC, vkurennov commented on app/assets/javascripts/templates/answer.jst.skim
> +    -if gon.current_user != null
еще может быть undefined

2017-09-09 09:12 UTC, vkurennov commented on app/assets/javascripts/comments.coffee
> +          mod = comment.commentable_type.toLowerCase()
И где используется эта переменная?

2017-09-09 09:12 UTC, vkurennov commented on app/assets/javascripts/comments.coffee
> +          $(".comment-#{id}").after(JST['templates/comment']({
Если у вопроса и ответа совпадут id, то комментарий добавится к обоим

2017-09-09 09:12 UTC, vkurennov commented on app/views/comments/create.js.erb
> +  $(".comment-<%= id %>").after("<%=  j render(@comment) %>");
Опять же, если id совпадут, то комментарий будет в 2-х местах

2017-09-10 08:21 UTC, vkurennov approved these changes

2017-09-10 09:03 UTC, merged